repos:
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
    - id: isort
      files: ^gastropy/
-   repo: https://github.com/ambv/black
    rev: 21.8b0
    hooks:
    - id: black
      language_version: python3
      files: ^gastropy/
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: flake8
      files: ^gastropy/
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.910'  # Use the sha / tag you want to point at
    hooks:
    - id: mypy 
      files: ^gastropy/
      args: [--ignore-missing-imports]